#!/usr/bin/perl

$| = 1;

sub sys {
    my $cmd = shift;
    print "*** $cmd\n";
    return system($cmd);
}

sys("rm -f config.cache");
sys("aclocal -I m4");
sys("autoconf");
sys("touch README AUTHORS NEWS ChangeLog");
sys("autoheader");
sys("automake -a");
#sys("./configure --enable-gltrace");
sys("CFLAGS=-g CXXFLAGS=-g ./configure");

