#define glClearIndex( ARGS ) glClearIndex ARGS
#define glClearColor( ARGS ) glClearColor ARGS
#define glClear( ARGS ) glClear ARGS
#define glIndexMask( ARGS ) glIndexMask ARGS
#define glColorMask( ARGS ) glColorMask ARGS
#define glAlphaFunc( ARGS ) glAlphaFunc ARGS
#define glBlendFunc( ARGS ) glBlendFunc ARGS
#define glLogicOp( ARGS ) glLogicOp ARGS
#define glCullFace( ARGS ) glCullFace ARGS
#define glFrontFace( ARGS ) glFrontFace ARGS
#define glPointSize( ARGS ) glPointSize ARGS
#define glLineWidth( ARGS ) glLineWidth ARGS
#define glLineStipple( ARGS ) glLineStipple ARGS
#define glPolygonMode( ARGS ) glPolygonMode ARGS
#define glPolygonOffset( ARGS ) glPolygonOffset ARGS
#define glPolygonStipple( ARGS ) glPolygonStipple ARGS
#define glGetPolygonStipple( ARGS ) glGetPolygonStipple ARGS
#define glEdgeFlag( ARGS ) glEdgeFlag ARGS
#define glEdgeFlagv( ARGS ) glEdgeFlagv ARGS
#define glScissor( ARGS ) glScissor ARGS
#define glClipPlane( ARGS ) glClipPlane ARGS
#define glGetClipPlane( ARGS ) glGetClipPlane ARGS
#define glDrawBuffer( ARGS ) glDrawBuffer ARGS
#define glReadBuffer( ARGS ) glReadBuffer ARGS
#define glEnable( ARGS ) glEnable ARGS
#define glDisable( ARGS ) glDisable ARGS
#define glIsEnabled( ARGS ) glIsEnabled ARGS
#define glEnableClientState( ARGS ) glEnableClientState ARGS
#define glDisableClientState( ARGS ) glDisableClientState ARGS
#define glGetBooleanv( ARGS ) glGetBooleanv ARGS
#define glGetDoublev( ARGS ) glGetDoublev ARGS
#define glGetFloatv( ARGS ) glGetFloatv ARGS
#define glGetIntegerv( ARGS ) glGetIntegerv ARGS
#define glPushAttrib( ARGS ) glPushAttrib ARGS
#define glPopAttrib( ARGS ) glPopAttrib ARGS
#define glPushClientAttrib( ARGS ) glPushClientAttrib ARGS
#define glPopClientAttrib( ARGS ) glPopClientAttrib ARGS
#define glRenderMode( ARGS ) glRenderMode ARGS
#define glGetError( ARGS ) glGetError ARGS
#define glFinish( ARGS ) glFinish ARGS
#define glFlush( ARGS ) glFlush ARGS
#define glHint( ARGS ) glHint ARGS
#define glClearDepth( ARGS ) glClearDepth ARGS
#define glDepthFunc( ARGS ) glDepthFunc ARGS
#define glDepthMask( ARGS ) glDepthMask ARGS
#define glDepthRange( ARGS ) glDepthRange ARGS
#define glClearAccum( ARGS ) glClearAccum ARGS
#define glAccum( ARGS ) glAccum ARGS
#define glMatrixMode( ARGS ) glMatrixMode ARGS
#define glOrtho( ARGS ) glOrtho ARGS
#define glFrustum( ARGS ) glFrustum ARGS
#define glViewport( ARGS ) glViewport ARGS
#define glPushMatrix( ARGS ) glPushMatrix ARGS
#define glPopMatrix( ARGS ) glPopMatrix ARGS
#define glLoadIdentity( ARGS ) glLoadIdentity ARGS
#define glLoadMatrixd( ARGS ) glLoadMatrixd ARGS
#define glLoadMatrixf( ARGS ) glLoadMatrixf ARGS
#define glMultMatrixd( ARGS ) glMultMatrixd ARGS
#define glMultMatrixf( ARGS ) glMultMatrixf ARGS
#define glRotated( ARGS ) glRotated ARGS
#define glRotatef( ARGS ) glRotatef ARGS
#define glScaled( ARGS ) glScaled ARGS
#define glScalef( ARGS ) glScalef ARGS
#define glTranslated( ARGS ) glTranslated ARGS
#define glTranslatef( ARGS ) glTranslatef ARGS
#define glIsList( ARGS ) glIsList ARGS
#define glDeleteLists( ARGS ) glDeleteLists ARGS
#define glGenLists( ARGS ) glGenLists ARGS
#define glNewList( ARGS ) glNewList ARGS
#define glEndList( ARGS ) glEndList ARGS
#define glCallList( ARGS ) glCallList ARGS
#define glCallLists( ARGS ) glCallLists ARGS
#define glListBase( ARGS ) glListBase ARGS
#define glBegin( ARGS ) glBegin ARGS
#define glEnd( ARGS ) glEnd ARGS
#define glVertex2d( ARGS ) glVertex2d ARGS
#define glVertex2f( ARGS ) glVertex2f ARGS
#define glVertex2i( ARGS ) glVertex2i ARGS
#define glVertex2s( ARGS ) glVertex2s ARGS
#define glVertex3d( ARGS ) glVertex3d ARGS
#define glVertex3f( ARGS ) glVertex3f ARGS
#define glVertex3i( ARGS ) glVertex3i ARGS
#define glVertex3s( ARGS ) glVertex3s ARGS
#define glVertex4d( ARGS ) glVertex4d ARGS
#define glVertex4f( ARGS ) glVertex4f ARGS
#define glVertex4i( ARGS ) glVertex4i ARGS
#define glVertex4s( ARGS ) glVertex4s ARGS
#define glVertex2dv( ARGS ) glVertex2dv ARGS
#define glVertex2fv( ARGS ) glVertex2fv ARGS
#define glVertex2iv( ARGS ) glVertex2iv ARGS
#define glVertex2sv( ARGS ) glVertex2sv ARGS
#define glVertex3dv( ARGS ) glVertex3dv ARGS
#define glVertex3fv( ARGS ) glVertex3fv ARGS
#define glVertex3iv( ARGS ) glVertex3iv ARGS
#define glVertex3sv( ARGS ) glVertex3sv ARGS
#define glVertex4dv( ARGS ) glVertex4dv ARGS
#define glVertex4fv( ARGS ) glVertex4fv ARGS
#define glVertex4iv( ARGS ) glVertex4iv ARGS
#define glVertex4sv( ARGS ) glVertex4sv ARGS
#define glNormal3b( ARGS ) glNormal3b ARGS
#define glNormal3d( ARGS ) glNormal3d ARGS
#define glNormal3f( ARGS ) glNormal3f ARGS
#define glNormal3i( ARGS ) glNormal3i ARGS
#define glNormal3s( ARGS ) glNormal3s ARGS
#define glNormal3bv( ARGS ) glNormal3bv ARGS
#define glNormal3dv( ARGS ) glNormal3dv ARGS
#define glNormal3fv( ARGS ) glNormal3fv ARGS
#define glNormal3iv( ARGS ) glNormal3iv ARGS
#define glNormal3sv( ARGS ) glNormal3sv ARGS
#define glIndexd( ARGS ) glIndexd ARGS
#define glIndexf( ARGS ) glIndexf ARGS
#define glIndexi( ARGS ) glIndexi ARGS
#define glIndexs( ARGS ) glIndexs ARGS
#define glIndexub( ARGS ) glIndexub ARGS
#define glIndexdv( ARGS ) glIndexdv ARGS
#define glIndexfv( ARGS ) glIndexfv ARGS
#define glIndexiv( ARGS ) glIndexiv ARGS
#define glIndexsv( ARGS ) glIndexsv ARGS
#define glIndexubv( ARGS ) glIndexubv ARGS
#define glColor3b( ARGS ) glColor3b ARGS
#define glColor3d( ARGS ) glColor3d ARGS
#define glColor3f( ARGS ) glColor3f ARGS
#define glColor3i( ARGS ) glColor3i ARGS
#define glColor3s( ARGS ) glColor3s ARGS
#define glColor3ub( ARGS ) glColor3ub ARGS
#define glColor3ui( ARGS ) glColor3ui ARGS
#define glColor3us( ARGS ) glColor3us ARGS
#define glColor4b( ARGS ) glColor4b ARGS
#define glColor4d( ARGS ) glColor4d ARGS
#define glColor4f( ARGS ) glColor4f ARGS
#define glColor4i( ARGS ) glColor4i ARGS
#define glColor4s( ARGS ) glColor4s ARGS
#define glColor4ub( ARGS ) glColor4ub ARGS
#define glColor4ui( ARGS ) glColor4ui ARGS
#define glColor4us( ARGS ) glColor4us ARGS
#define glColor3bv( ARGS ) glColor3bv ARGS
#define glColor3dv( ARGS ) glColor3dv ARGS
#define glColor3fv( ARGS ) glColor3fv ARGS
#define glColor3iv( ARGS ) glColor3iv ARGS
#define glColor3sv( ARGS ) glColor3sv ARGS
#define glColor3ubv( ARGS ) glColor3ubv ARGS
#define glColor3uiv( ARGS ) glColor3uiv ARGS
#define glColor3usv( ARGS ) glColor3usv ARGS
#define glColor4bv( ARGS ) glColor4bv ARGS
#define glColor4dv( ARGS ) glColor4dv ARGS
#define glColor4fv( ARGS ) glColor4fv ARGS
#define glColor4iv( ARGS ) glColor4iv ARGS
#define glColor4sv( ARGS ) glColor4sv ARGS
#define glColor4ubv( ARGS ) glColor4ubv ARGS
#define glColor4uiv( ARGS ) glColor4uiv ARGS
#define glColor4usv( ARGS ) glColor4usv ARGS
#define glTexCoord1d( ARGS ) glTexCoord1d ARGS
#define glTexCoord1f( ARGS ) glTexCoord1f ARGS
#define glTexCoord1i( ARGS ) glTexCoord1i ARGS
#define glTexCoord1s( ARGS ) glTexCoord1s ARGS
#define glTexCoord2d( ARGS ) glTexCoord2d ARGS
#define glTexCoord2f( ARGS ) glTexCoord2f ARGS
#define glTexCoord2i( ARGS ) glTexCoord2i ARGS
#define glTexCoord2s( ARGS ) glTexCoord2s ARGS
#define glTexCoord3d( ARGS ) glTexCoord3d ARGS
#define glTexCoord3f( ARGS ) glTexCoord3f ARGS
#define glTexCoord3i( ARGS ) glTexCoord3i ARGS
#define glTexCoord3s( ARGS ) glTexCoord3s ARGS
#define glTexCoord4d( ARGS ) glTexCoord4d ARGS
#define glTexCoord4f( ARGS ) glTexCoord4f ARGS
#define glTexCoord4i( ARGS ) glTexCoord4i ARGS
#define glTexCoord4s( ARGS ) glTexCoord4s ARGS
#define glTexCoord1dv( ARGS ) glTexCoord1dv ARGS
#define glTexCoord1fv( ARGS ) glTexCoord1fv ARGS
#define glTexCoord1iv( ARGS ) glTexCoord1iv ARGS
#define glTexCoord1sv( ARGS ) glTexCoord1sv ARGS
#define glTexCoord2dv( ARGS ) glTexCoord2dv ARGS
#define glTexCoord2fv( ARGS ) glTexCoord2fv ARGS
#define glTexCoord2iv( ARGS ) glTexCoord2iv ARGS
#define glTexCoord2sv( ARGS ) glTexCoord2sv ARGS
#define glTexCoord3dv( ARGS ) glTexCoord3dv ARGS
#define glTexCoord3fv( ARGS ) glTexCoord3fv ARGS
#define glTexCoord3iv( ARGS ) glTexCoord3iv ARGS
#define glTexCoord3sv( ARGS ) glTexCoord3sv ARGS
#define glTexCoord4dv( ARGS ) glTexCoord4dv ARGS
#define glTexCoord4fv( ARGS ) glTexCoord4fv ARGS
#define glTexCoord4iv( ARGS ) glTexCoord4iv ARGS
#define glTexCoord4sv( ARGS ) glTexCoord4sv ARGS
#define glRasterPos2d( ARGS ) glRasterPos2d ARGS
#define glRasterPos2f( ARGS ) glRasterPos2f ARGS
#define glRasterPos2i( ARGS ) glRasterPos2i ARGS
#define glRasterPos2s( ARGS ) glRasterPos2s ARGS
#define glRasterPos3d( ARGS ) glRasterPos3d ARGS
#define glRasterPos3f( ARGS ) glRasterPos3f ARGS
#define glRasterPos3i( ARGS ) glRasterPos3i ARGS
#define glRasterPos3s( ARGS ) glRasterPos3s ARGS
#define glRasterPos4d( ARGS ) glRasterPos4d ARGS
#define glRasterPos4f( ARGS ) glRasterPos4f ARGS
#define glRasterPos4i( ARGS ) glRasterPos4i ARGS
#define glRasterPos4s( ARGS ) glRasterPos4s ARGS
#define glRasterPos2dv( ARGS ) glRasterPos2dv ARGS
#define glRasterPos2fv( ARGS ) glRasterPos2fv ARGS
#define glRasterPos2iv( ARGS ) glRasterPos2iv ARGS
#define glRasterPos2sv( ARGS ) glRasterPos2sv ARGS
#define glRasterPos3dv( ARGS ) glRasterPos3dv ARGS
#define glRasterPos3fv( ARGS ) glRasterPos3fv ARGS
#define glRasterPos3iv( ARGS ) glRasterPos3iv ARGS
#define glRasterPos3sv( ARGS ) glRasterPos3sv ARGS
#define glRasterPos4dv( ARGS ) glRasterPos4dv ARGS
#define glRasterPos4fv( ARGS ) glRasterPos4fv ARGS
#define glRasterPos4iv( ARGS ) glRasterPos4iv ARGS
#define glRasterPos4sv( ARGS ) glRasterPos4sv ARGS
#define glRectd( ARGS ) glRectd ARGS
#define glRectf( ARGS ) glRectf ARGS
#define glRecti( ARGS ) glRecti ARGS
#define glRects( ARGS ) glRects ARGS
#define glRectdv( ARGS ) glRectdv ARGS
#define glRectfv( ARGS ) glRectfv ARGS
#define glRectiv( ARGS ) glRectiv ARGS
#define glRectsv( ARGS ) glRectsv ARGS
#define glVertexPointer( ARGS ) glVertexPointer ARGS
#define glNormalPointer( ARGS ) glNormalPointer ARGS
#define glColorPointer( ARGS ) glColorPointer ARGS
#define glIndexPointer( ARGS ) glIndexPointer ARGS
#define glTexCoordPointer( ARGS ) glTexCoordPointer ARGS
#define glEdgeFlagPointer( ARGS ) glEdgeFlagPointer ARGS
#define glGetPointerv( ARGS ) glGetPointerv ARGS
#define glArrayElement( ARGS ) glArrayElement ARGS
#define glDrawArrays( ARGS ) glDrawArrays ARGS
#define glDrawElements( ARGS ) glDrawElements ARGS
#define glInterleavedArrays( ARGS ) glInterleavedArrays ARGS
#define glShadeModel( ARGS ) glShadeModel ARGS
#define glLightf( ARGS ) glLightf ARGS
#define glLighti( ARGS ) glLighti ARGS
#define glLightfv( ARGS ) glLightfv ARGS
#define glLightiv( ARGS ) glLightiv ARGS
#define glGetLightfv( ARGS ) glGetLightfv ARGS
#define glGetLightiv( ARGS ) glGetLightiv ARGS
#define glLightModelf( ARGS ) glLightModelf ARGS
#define glLightModeli( ARGS ) glLightModeli ARGS
#define glLightModelfv( ARGS ) glLightModelfv ARGS
#define glLightModeliv( ARGS ) glLightModeliv ARGS
#define glMaterialf( ARGS ) glMaterialf ARGS
#define glMateriali( ARGS ) glMateriali ARGS
#define glMaterialfv( ARGS ) glMaterialfv ARGS
#define glMaterialiv( ARGS ) glMaterialiv ARGS
#define glGetMaterialfv( ARGS ) glGetMaterialfv ARGS
#define glGetMaterialiv( ARGS ) glGetMaterialiv ARGS
#define glColorMaterial( ARGS ) glColorMaterial ARGS
#define glPixelZoom( ARGS ) glPixelZoom ARGS
#define glPixelStoref( ARGS ) glPixelStoref ARGS
#define glPixelStorei( ARGS ) glPixelStorei ARGS
#define glPixelTransferf( ARGS ) glPixelTransferf ARGS
#define glPixelTransferi( ARGS ) glPixelTransferi ARGS
#define glPixelMapfv( ARGS ) glPixelMapfv ARGS
#define glPixelMapuiv( ARGS ) glPixelMapuiv ARGS
#define glPixelMapusv( ARGS ) glPixelMapusv ARGS
#define glGetPixelMapfv( ARGS ) glGetPixelMapfv ARGS
#define glGetPixelMapuiv( ARGS ) glGetPixelMapuiv ARGS
#define glGetPixelMapusv( ARGS ) glGetPixelMapusv ARGS
#define glBitmap( ARGS ) glBitmap ARGS
#define glReadPixels( ARGS ) glReadPixels ARGS
#define glDrawPixels( ARGS ) glDrawPixels ARGS
#define glCopyPixels( ARGS ) glCopyPixels ARGS
#define glStencilFunc( ARGS ) glStencilFunc ARGS
#define glStencilMask( ARGS ) glStencilMask ARGS
#define glStencilOp( ARGS ) glStencilOp ARGS
#define glClearStencil( ARGS ) glClearStencil ARGS
#define glTexGend( ARGS ) glTexGend ARGS
#define glTexGenf( ARGS ) glTexGenf ARGS
#define glTexGeni( ARGS ) glTexGeni ARGS
#define glTexGendv( ARGS ) glTexGendv ARGS
#define glTexGenfv( ARGS ) glTexGenfv ARGS
#define glTexGeniv( ARGS ) glTexGeniv ARGS
#define glGetTexGendv( ARGS ) glGetTexGendv ARGS
#define glGetTexGenfv( ARGS ) glGetTexGenfv ARGS
#define glGetTexGeniv( ARGS ) glGetTexGeniv ARGS
#define glTexEnvf( ARGS ) glTexEnvf ARGS
#define glTexEnvi( ARGS ) glTexEnvi ARGS
#define glTexEnvfv( ARGS ) glTexEnvfv ARGS
#define glTexEnviv( ARGS ) glTexEnviv ARGS
#define glGetTexEnvfv( ARGS ) glGetTexEnvfv ARGS
#define glGetTexEnviv( ARGS ) glGetTexEnviv ARGS
#define glTexParameterf( ARGS ) glTexParameterf ARGS
#define glTexParameteri( ARGS ) glTexParameteri ARGS
#define glTexParameterfv( ARGS ) glTexParameterfv ARGS
#define glTexParameteriv( ARGS ) glTexParameteriv ARGS
#define glGetTexParameterfv( ARGS ) glGetTexParameterfv ARGS
#define glGetTexParameteriv( ARGS ) glGetTexParameteriv ARGS
#define glGetTexLevelParameterfv( ARGS ) glGetTexLevelParameterfv ARGS
#define glGetTexLevelParameteriv( ARGS ) glGetTexLevelParameteriv ARGS
#define glTexImage1D( ARGS ) glTexImage1D ARGS
#define glTexImage2D( ARGS ) glTexImage2D ARGS
#define glGetTexImage( ARGS ) glGetTexImage ARGS
#define glGenTextures( ARGS ) glGenTextures ARGS
#define glDeleteTextures( ARGS ) glDeleteTextures ARGS
#define glBindTexture( ARGS ) glBindTexture ARGS
#define glPrioritizeTextures( ARGS ) glPrioritizeTextures ARGS
#define glAreTexturesResident( ARGS ) glAreTexturesResident ARGS
#define glIsTexture( ARGS ) glIsTexture ARGS
#define glTexSubImage1D( ARGS ) glTexSubImage1D ARGS
#define glTexSubImage2D( ARGS ) glTexSubImage2D ARGS
#define glCopyTexImage1D( ARGS ) glCopyTexImage1D ARGS
#define glCopyTexImage2D( ARGS ) glCopyTexImage2D ARGS
#define glCopyTexSubImage1D( ARGS ) glCopyTexSubImage1D ARGS
#define glCopyTexSubImage2D( ARGS ) glCopyTexSubImage2D ARGS
#define glMap1d( ARGS ) glMap1d ARGS
#define glMap1f( ARGS ) glMap1f ARGS
#define glMap2d( ARGS ) glMap2d ARGS
#define glMap2f( ARGS ) glMap2f ARGS
#define glGetMapdv( ARGS ) glGetMapdv ARGS
#define glGetMapfv( ARGS ) glGetMapfv ARGS
#define glGetMapiv( ARGS ) glGetMapiv ARGS
#define glEvalCoord1d( ARGS ) glEvalCoord1d ARGS
#define glEvalCoord1f( ARGS ) glEvalCoord1f ARGS
#define glEvalCoord1dv( ARGS ) glEvalCoord1dv ARGS
#define glEvalCoord1fv( ARGS ) glEvalCoord1fv ARGS
#define glEvalCoord2d( ARGS ) glEvalCoord2d ARGS
#define glEvalCoord2f( ARGS ) glEvalCoord2f ARGS
#define glEvalCoord2dv( ARGS ) glEvalCoord2dv ARGS
#define glEvalCoord2fv( ARGS ) glEvalCoord2fv ARGS
#define glMapGrid1d( ARGS ) glMapGrid1d ARGS
#define glMapGrid1f( ARGS ) glMapGrid1f ARGS
#define glMapGrid2d( ARGS ) glMapGrid2d ARGS
#define glMapGrid2f( ARGS ) glMapGrid2f ARGS
#define glEvalPoint1( ARGS ) glEvalPoint1 ARGS
#define glEvalPoint2( ARGS ) glEvalPoint2 ARGS
#define glEvalMesh1( ARGS ) glEvalMesh1 ARGS
#define glEvalMesh2( ARGS ) glEvalMesh2 ARGS
#define glFogf( ARGS ) glFogf ARGS
#define glFogi( ARGS ) glFogi ARGS
#define glFogfv( ARGS ) glFogfv ARGS
#define glFogiv( ARGS ) glFogiv ARGS
#define glFeedbackBuffer( ARGS ) glFeedbackBuffer ARGS
#define glPassThrough( ARGS ) glPassThrough ARGS
#define glSelectBuffer( ARGS ) glSelectBuffer ARGS
#define glInitNames( ARGS ) glInitNames ARGS
#define glLoadName( ARGS ) glLoadName ARGS
#define glPushName( ARGS ) glPushName ARGS
#define glPopName( ARGS ) glPopName ARGS
#define glDrawRangeElements( ARGS ) glDrawRangeElements ARGS
#define glTexImage3D( ARGS ) glTexImage3D ARGS
#define glTexSubImage3D( ARGS ) glTexSubImage3D ARGS
#define glCopyTexSubImage3D( ARGS ) glCopyTexSubImage3D ARGS
#define glColorTable( ARGS ) glColorTable ARGS
#define glColorSubTable( ARGS ) glColorSubTable ARGS
#define glColorTableParameteriv( ARGS ) glColorTableParameteriv ARGS
#define glColorTableParameterfv( ARGS ) glColorTableParameterfv ARGS
#define glCopyColorSubTable( ARGS ) glCopyColorSubTable ARGS
#define glCopyColorTable( ARGS ) glCopyColorTable ARGS
#define glGetColorTable( ARGS ) glGetColorTable ARGS
#define glGetColorTableParameterfv( ARGS ) glGetColorTableParameterfv ARGS
#define glGetColorTableParameteriv( ARGS ) glGetColorTableParameteriv ARGS
#define glBlendEquation( ARGS ) glBlendEquation ARGS
#define glBlendColor( ARGS ) glBlendColor ARGS
#define glHistogram( ARGS ) glHistogram ARGS
#define glResetHistogram( ARGS ) glResetHistogram ARGS
#define glGetHistogram( ARGS ) glGetHistogram ARGS
#define glGetHistogramParameterfv( ARGS ) glGetHistogramParameterfv ARGS
#define glGetHistogramParameteriv( ARGS ) glGetHistogramParameteriv ARGS
#define glMinmax( ARGS ) glMinmax ARGS
#define glResetMinmax( ARGS ) glResetMinmax ARGS
#define glGetMinmax( ARGS ) glGetMinmax ARGS
#define glGetMinmaxParameterfv( ARGS ) glGetMinmaxParameterfv ARGS
#define glGetMinmaxParameteriv( ARGS ) glGetMinmaxParameteriv ARGS
#define glConvolutionFilter1D( ARGS ) glConvolutionFilter1D ARGS
#define glConvolutionFilter2D( ARGS ) glConvolutionFilter2D ARGS
#define glConvolutionParameterf( ARGS ) glConvolutionParameterf ARGS
#define glConvolutionParameterfv( ARGS ) glConvolutionParameterfv ARGS
#define glConvolutionParameteri( ARGS ) glConvolutionParameteri ARGS
#define glConvolutionParameteriv( ARGS ) glConvolutionParameteriv ARGS
#define glCopyConvolutionFilter1D( ARGS ) glCopyConvolutionFilter1D ARGS
#define glCopyConvolutionFilter2D( ARGS ) glCopyConvolutionFilter2D ARGS
#define glGetConvolutionFilter( ARGS ) glGetConvolutionFilter ARGS
#define glGetConvolutionParameterfv( ARGS ) glGetConvolutionParameterfv ARGS
#define glGetConvolutionParameteriv( ARGS ) glGetConvolutionParameteriv ARGS
#define glSeparableFilter2D( ARGS ) glSeparableFilter2D ARGS
#define glGetSeparableFilter( ARGS ) glGetSeparableFilter ARGS
#define glActiveTextureARB( ARGS ) glActiveTextureARB ARGS
#define glClientActiveTextureARB( ARGS ) glClientActiveTextureARB ARGS
#define glMultiTexCoord1dARB( ARGS ) glMultiTexCoord1dARB ARGS
#define glMultiTexCoord1dvARB( ARGS ) glMultiTexCoord1dvARB ARGS
#define glMultiTexCoord1fARB( ARGS ) glMultiTexCoord1fARB ARGS
#define glMultiTexCoord1fvARB( ARGS ) glMultiTexCoord1fvARB ARGS
#define glMultiTexCoord1iARB( ARGS ) glMultiTexCoord1iARB ARGS
#define glMultiTexCoord1ivARB( ARGS ) glMultiTexCoord1ivARB ARGS
#define glMultiTexCoord1sARB( ARGS ) glMultiTexCoord1sARB ARGS
#define glMultiTexCoord1svARB( ARGS ) glMultiTexCoord1svARB ARGS
#define glMultiTexCoord2dARB( ARGS ) glMultiTexCoord2dARB ARGS
#define glMultiTexCoord2dvARB( ARGS ) glMultiTexCoord2dvARB ARGS
#define glMultiTexCoord2fARB( ARGS ) glMultiTexCoord2fARB ARGS
#define glMultiTexCoord2fvARB( ARGS ) glMultiTexCoord2fvARB ARGS
#define glMultiTexCoord2iARB( ARGS ) glMultiTexCoord2iARB ARGS
#define glMultiTexCoord2ivARB( ARGS ) glMultiTexCoord2ivARB ARGS
#define glMultiTexCoord2sARB( ARGS ) glMultiTexCoord2sARB ARGS
#define glMultiTexCoord2svARB( ARGS ) glMultiTexCoord2svARB ARGS
#define glMultiTexCoord3dARB( ARGS ) glMultiTexCoord3dARB ARGS
#define glMultiTexCoord3dvARB( ARGS ) glMultiTexCoord3dvARB ARGS
#define glMultiTexCoord3fARB( ARGS ) glMultiTexCoord3fARB ARGS
#define glMultiTexCoord3fvARB( ARGS ) glMultiTexCoord3fvARB ARGS
#define glMultiTexCoord3iARB( ARGS ) glMultiTexCoord3iARB ARGS
#define glMultiTexCoord3ivARB( ARGS ) glMultiTexCoord3ivARB ARGS
#define glMultiTexCoord3sARB( ARGS ) glMultiTexCoord3sARB ARGS
#define glMultiTexCoord3svARB( ARGS ) glMultiTexCoord3svARB ARGS
#define glMultiTexCoord4dARB( ARGS ) glMultiTexCoord4dARB ARGS
#define glMultiTexCoord4dvARB( ARGS ) glMultiTexCoord4dvARB ARGS
#define glMultiTexCoord4fARB( ARGS ) glMultiTexCoord4fARB ARGS
#define glMultiTexCoord4fvARB( ARGS ) glMultiTexCoord4fvARB ARGS
#define glMultiTexCoord4iARB( ARGS ) glMultiTexCoord4iARB ARGS
#define glMultiTexCoord4ivARB( ARGS ) glMultiTexCoord4ivARB ARGS
#define glMultiTexCoord4sARB( ARGS ) glMultiTexCoord4sARB ARGS
#define glMultiTexCoord4svARB( ARGS ) glMultiTexCoord4svARB ARGS
